{
    "name": "Uploads",
    "description": "Upload & store files in an object store.",
    "icon": "file-arrow-up",
    "tags": [
        "core",
        "utility"
    ],
    "authors": [
        "rivet-gg",
        "Blckbrry-Pi",
        "NathanFlurry"
    ],
    "status": "stable",
    "scripts": {
        "prepare": {
            "name": "Prepare Upload",
            "description": "Prepare an upload batch for data transfer"
        },
        "complete": {
            "name": "Complete Upload",
            "description": "Alert the module that the upload has been completed"
        },
        "get": {
            "name": "Get Upload Metadata",
            "description": "Get the metadata (including contained files) for specified upload IDs"
        },
        "get_public_file_urls": {
            "name": "Get File Link",
            "description": "Get presigned download links for each of the specified files"
        },
        "delete": {
            "name": "Delete Upload",
            "description": "Removes the upload and deletes the files from the bucket"
        }
    },
    "errors": {
        "no_files": {
            "name": "No Files Provided",
            "description": "An upload must have at least 1 file"
        },
        "too_many_files": {
            "name": "Too Many Files Provided",
            "description": "There is a limit to how many files can be put into a single upload (see config)"
        },
        "duplicate_paths": {
            "name": "Duplicate Paths Provided",
            "description": "An upload cannot contain 2 files with the same paths (see `cause` for offending paths)"
        },
        "size_limit_exceeded": {
            "name": "Combined Size Limit Exceeded",
            "description": "There is a maximum total size per upload (see config)"
        },
        "upload_not_found": {
            "name": "Upload Not Found",
            "description": "The provided upload ID didn't match any known existing uploads"
        },
        "upload_already_completed": {
            "name": "Upload Already completed",
            "description": "\\`complete\\` was already called on this upload"
        },
        "s3_not_configured": {
            "name": "S3 Not Configured",
            "description": "The S3 bucket is not configured (missing env variables)"
        },
        "too_many_chunks": {
            "name": "Possibility Of Too Many Chunks",
            "description": "AWS S3 has a limit on the number of parts that can be uploaded in a\nmultipart upload. This limit is 10,000 parts. If the number of chunks\nrequired to upload the maximum multipart upload size exceeds this limit,\nany operation will preemptively throw this error.\n"
        },
        "multipart_upload_completion_fail": {
            "name": "Multipart Upload Completion Failure",
            "description": "The multipart upload failed to complete (see `cause` for more information)"
        }
    },
    "dependencies": {}
}
